# Generated by Django 2.2.12 on 2020-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
                ('transmission_time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
