# Generated by Django 2.2.12 on 2020-12-29 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='transmission_time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
