# Generated by Django 3.1.5 on 2021-01-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201229_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
